### ISSUE TITLE
Crash 1.19.2

### ISSUE THREAD

**Issue by QianFuv** [rejahtavi/betterflight#12]
https://mclo.gs/JSRRNAo

**Comment by ArkVeil** [comment]
Hi, thank you for the report! Could I ask a few details while I look into this?

Did this crash when you were launching the client or when you were trying to load the world? Is this a server environment or single player? Does the crash happen with just Better Flight?

**Comment by ArkVeil** [comment]
Try the newest version. BetterFlight-1.19.2-forge-1.1.2.

**Comment by QianFuv** [comment]
The client environment crashed while starting the game.
I had a crash after I installed better flight, but it went back to normal when I disabled it.
I'll try the new version later, please wait a moment.

**Comment by QianFuv** [comment]
After my testing, the 1.1.2 version worked fine. Thank you for your efforts!
