### ISSUE TITLE
Unable to find the config file on server

### ISSUE THREAD

**Issue by AlanRenault** [rejahtavi/betterflight#2]
Hi!

Thank you for this mod, it works very well but I can't find the config file on the server side to tweak it a little bit.
Is this a bug ?

Thank you :)

**Comment by rejahtavi** [comment]
Forge saves all server side configs with each world independently in /server/saves/world/serverconfig/.

If you want your changes to apply to any newly created worlds, once you are happy with the config, copy it to /server/defaultconfigs/.

Stuff in /defaultconfigs/ does nothing on its own, but is copied to the /serverconfig/ folder of every new world automatically.
