### ISSUE TITLE
[Feature Request] Take off key bind / config

### ISSUE THREAD

**Issue by Tcat2000** [rejahtavi/betterflight#7]
It is a bit annoying how easy it is to accidentally take off, like if you sprint jump and get your timing off, it launches you into the air. I suggest you add a config, which then requires a key bind to take off.

so Xconfig = true, functions as normal
but Xconfig = false, instead of jumping while in the air you will press, say, 'r'

Actually playing a small pack i put together, and just got an elytra, and having this issue.

**Comment by ArkVeil** [comment]
I'm not sure if I'll implement it exactly this way, but this issue was bothering me too. I'm experimenting with changes in how the mod propels you, so I'll be thinking about this while I do so.

**Comment by Tcat2000** [comment]
ok cool
